Data Analysis - Numpy Tutorial 

In [ ]:
****************   Variables   **************** 

In [6]:
# one dimension array 
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# more than one dimensions 
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
# more than one dimensions 
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
****************    Ndarray Object   **************** 
   Parameters of ndarray Object
     numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

In [9]:
# minimum dimension - ndmin 
import numpy as np
a=np.array([1,2,3], ndmin=0)
print(a)

[1 2 3]


In [10]:
# minimum dimension - ndmin 
import numpy as np
a=np.array([1,2,3], ndmin=1)
print(a)

[1 2 3]


In [11]:
# minimum dimension - ndmin 
import numpy as np
a=np.array([1,2,3], ndmin=3)
print(a)

[[[1 2 3]]]


In [12]:
# minimum dimension - ndmin 
import numpy as np
a=np.array([1,2,3], ndmin=5)
print(a)

[[[[[1 2 3]]]]]


In [13]:
# Datatype Parameter - dtype 
import numpy as np
a=np.array([1,2,3], dtype=int)
print(a)

[1 2 3]


In [14]:
# Datatype Parameter - dtype 
import numpy as np
a=np.array([1,2,3], dtype=float)
print(a)

[1. 2. 3.]


In [15]:
# Datatype Parameter - dtype 
import numpy as np
a=np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
****************    Data Type Objects (dtype)   **************** 

In [17]:
import numpy as np
a=np.dtype(np.int32)
print (a)

int32


In [23]:
import numpy as np
a=np.dtype(np.int64)
print (a)

int64


In [24]:
import numpy as np
a=np.dtype('<i4')
print (a)

int32


In [22]:
# First Create a structured datatype
import numpy as np
a=np.dtype([('age',np.int32)])
print (a)

[('age', '<i4')]


In [ ]:
# Now apply it to ndarray object 

In [1]:
import numpy as np
a=np.dtype([('age',np.int32)])
b=np.array([45,56,43,55],dtype='a')
print(b)

[b'45' b'56' b'43' b'55']


In [2]:
# One more example - creating a structured object and applying it to ndarray
import numpy as np
x=np.dtype([('gps location', np.float64) ])
a=np.array([32.9348754905, 43.5879826595], dtype=x)
print (a)

[(32.93487549,) (43.58798266,)]


In [11]:
# One more example using string - creating a structured object and applying it to ndarray
import numpy as np
x=np.dtype([('name','S20')])
a=np.array(['John','Mark'],dtype=x)
print(a)

[(b'John',) (b'Mark',)]


In [2]:
# Using multiple fields
import numpy as np
a=np.dtype([('name','S20'),('age','int32'),('roll no','int64')])
b=np.array([('John','18','111334'),('Roe','19','111345'),('Tim','19','111367')], dtype=a)
print(b)

[(b'John', 18, 111334) (b'Roe', 19, 111345) (b'Tim', 19, 111367)]


In [ ]:
****************    NumPy - Array Attributes   **************** 

Things can we do using array in NumPy:
    1. Creating an array
    2. Reshaping an array with and without using reshape function
    3. Splitting an array
    4. Filling array with empty, zeros, ones
    5. Converting list to ndarray
    6. Array with numerical ranges with start, stop, steps parameter
    7. linspace, logspace
    8. Indexing and Slicing
    9. Advanced Indexing
    10.Broadcasting
    11.Iterating and Iterating over array

In [15]:
# simple array - One Dimensional Array
import numpy as np
a=np.array([1,2,3])
print (a)

[1 2 3]


In [21]:
# simple array - Two Dimensional Array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [24]:
# ndarray.shape
import numpy as np
a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns
print (a.shape)

(2, 3)


In [30]:
# resizing the ndarray
import numpy as np
a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns resize to 3 rows 2 column
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [1]:
# resizing the ndarray
import numpy as np
a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns resize to 6 rows 1 column
a.shape=(6,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [33]:
# resizing the ndarray using reshape function
import numpy as np
a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns resize to 3 rows 2 column
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
# resizing the ndarray using reshape function
import numpy as np
a=np.array([[1,2,3,4],[4,5,6,7]])    
b=a.reshape(2,2,2)              # Creating three dimensional array
print(b)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [35]:
# resizing the ndarray using reshape function
import numpy as np
a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns resize to 6 rows 1 column
b=a.reshape(6,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
# using ndarray.arange - One dimensional array
import numpy as np
a=np.arange(10)           # range from 0 1o 9
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
# Splitting the above program into two dimensional array
# ndim and shape
import numpy as np
a=np.arange(9)
a.ndim
a.shape=(3,3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [52]:
# Splitting the above program into three dimensional array
# ndim and shape
import numpy as np
a=np.arange(8)
a.ndim
a.shape=(2,2,2)
print(a)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [53]:
# Splitting the above program into three dimensional array
# ndim and reshape function
import numpy as np
a=np.arange(8)
a.ndim
b= a.reshape(2,2,2)
print(b)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [58]:
# numpy.itemsize 
# returns the length of each element of array in bytes.

import numpy as np
a=np.array([1,2,3], 'int32')
print (a.itemsize)


4


In [59]:
import numpy as np
a=np.array([1,2,3], 'int64')
print (a.itemsize)

8


In [61]:
import numpy as np
a=np.array([1,2,3,5,6,7], 'float32')
print (a.itemsize)

4


In [63]:
import numpy as np
a=np.array([1,2,3], dtype='int64')
print (a.itemsize)

8


In [65]:
# numpy.flags
# current values of all attributes in the object are returned

import numpy as np
a=np.array([1,2,3])
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [69]:
# numpy.empty
# creates an uninitialized array of specified shape and dtype

import numpy as np
a=np.empty([2,3])
print(a)

#values are randomly assigned
#default datatype is float

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [74]:
# another example with datatype defined

import numpy as np
a=np.empty([2,3], dtype='int')
print(a)

[[1 2 3]
 [4 5 6]]


In [75]:
# numpy.zeros
# Returns a new array of specified size, filled with zeros

import numpy as np
a=np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [79]:
# numpy.ones
# Returns a new array of specified size, filled with ones

import numpy as np
a=np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [80]:
import numpy as np
a=np.ones([2,3], dtype='int32')
print(a)

[[1 1 1]
 [1 1 1]]


In [84]:
# numpy.asarray
# converting list to ndarray

import numpy as np
a=(1,2,3)
b=np.asarray(a)
print(b)

[1 2 3]


In [87]:
import numpy as np
a=('a','b')
b=np.asarray(a)
print(b)

['a' 'b']


In [89]:
import numpy as np
a=(1,2,3)
b=np.asarray(a, dtype='float')
print(b)

[1. 2. 3.]


In [90]:
import numpy as np
a=(1,2,3),(4,5,6)
b=np.asarray(a, dtype='float')
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
****************   NumPy - Array From Numerical Ranges   ****************

In [ ]:
# numpy.arange
# This function returns an ndarray object containing evenly spaced values within a given range.

In [4]:
import numpy as np
x=np.arange(5)
print (x)

[0 1 2 3 4]


In [5]:
# Above program with datatype fixed
import numpy as np
x=np.arange(5,dtype='float32')
print(x)

[0. 1. 2. 3. 4.]


In [8]:
# With start and stop parameters
import numpy as np
x=np.arange(1,20)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
# With start and stop parameters along with increment
import numpy as np
x=np.arange(1,20,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# numpy.linspace
# Instead of step size, the number of evenly spaced values between the interval is specified.

In [11]:
import numpy as np
x=np.linspace(1,20,3)
print (x)

[ 1.  10.5 20. ]


In [16]:
# Another example
import numpy as np
x=np.linspace(0,20,5)
print (x)

[ 0.  5. 10. 15. 20.]


In [28]:
# Above example with endpoint set to false
import numpy as np
x=np.linspace(0,20,5, endpoint = False)
print (x)

[ 0.  4.  8. 12. 16.]


In [31]:
# Finding steps between the consecutive numbers using retstep
import numpy as np
x=np.linspace(0,20,5, retstep=True)
print (x)

(array([ 0.,  5., 10., 15., 20.]), 5.0)


In [33]:
# numpy.logspace
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [38]:
# Above program without setting base. The default base is 10.
import numpy as np 
a = np.logspace(1,10,num = 10) 
print (a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [ ]:
****************    Numpy Indexing and Slicing   ****************

In [ ]:
# Slice Function

In [46]:
import numpy as np
a=np.arange(10)
b=slice(2,8)
print(a[b])

[2 3 4 5 6 7]


In [49]:
# The above program could be also written as 
import numpy as np
a=np.arange(10)
b=a[2:8]
print(b)

[2 3 4 5 6 7]


In [1]:
import numpy as np
a=np.arange(10)
b=slice(2,8,2)
print(a[b])

[2 4 6]


In [3]:
import numpy as np         #using step
a=np.arange(10)
b=a[2:8:2]
print(b)

[2 4 6]


In [14]:
# Slicing the arrays

import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)    # Printing array

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [13]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:])     # slice items starting from index

[[3 4 5]
 [4 5 6]]


In [15]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[2:])     # slice items starting from index

[[4 5 6]]


In [19]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:2])     # slice items starting from index to end index

[[3 4 5]]


In [20]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:2,1:2])     # slice items starting from index to end index

[[4]]


In [23]:
# Printing nth row using ellipsis (...)
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1,...])

[3 4 5]


In [21]:
# Printing nth column using ellipsis (...)
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[...,1])

[2 4 5]


In [24]:
# Printing from nth row using ellipsis (...)
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:,...])

[[3 4 5]
 [4 5 6]]


In [26]:
# Printing from nth column using ellipsis (...)
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


In [ ]:
****************    Advanced Numpy Indexing     ****************

In [7]:
import numpy as np 
x = np.array([[1,2,3],[4,5,6],[7,8,9]])   
print (x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np 
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
y = x[[0,1,2], [0,1,0]]   
print (y)
# 0th row and 0th column is 1, next 1st row and 1st column is 5, 2nd row and 0th column us 7

[1 5 7]


In [1]:
import numpy as np 
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

rows = np.array([[0,0],[2,2]])
cols = np.array([[0,1],[0,1]]) 

y = x[rows,cols] 
print (y)

# (0,0)=1, (0,1)=2, (2,0)=7, (2,1)=8

[[1 2]
 [7 8]]


In [21]:
# Lets see slicing again
import numpy as np
x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
y=x[0:3,1:4]
print(y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [23]:
# Slicing using advanced index column
import numpy as np
x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
y=x[0:3,[2,3]]
print(y)

[[ 3  4]
 [ 6  7]
 [ 9 10]]


In [25]:
# Boolean Indexing
import numpy as np
x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
y=[x>6]
print(y)

[array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])]


In [29]:
import numpy as np
x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
print(x[x>6])

[ 7  8  7  8  9 10 11 10 11 12 13 14]


In [38]:
# Not a Number NaN
import numpy as np
a = np.array([[np.nan,2,3],[3,np.nan,5],[4,5,6]]) 
print(a)

[[nan  2.  3.]
 [ 3. nan  5.]
 [ 4.  5.  6.]]


In [35]:
# Printing NaN from the given array
import numpy as np
a = np.array([[np.nan,2,3],[3,np.nan,5],[4,5,6]]) 
print(a[np.isnan(a)])

[nan nan]


In [37]:
# Printing all the items in the array except NaN
import numpy as np
a = np.array([[np.nan,2,3],[3,np.nan,5],[4,5,6]]) 
print(a[~np.isnan(a)])

[2. 3. 3. 5. 4. 5. 6.]


In [ ]:
****************    Broadcasting     ****************

In [45]:
# Simple Array addition
import numpy as np
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=a+b
print(c)

[[5 7 9]]


In [46]:
# Simple Array Multiplication
import numpy as np
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=a*b
print(c)

[[ 4 10 18]]


In [48]:
# Two dimensional array - Addition
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4]])
c=a+b
print(c)

[[ 3  5  7]
 [ 6  8 10]]


In [49]:
# Two dimensional array - Multiplication
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4]])
c=a*b
print(c)

[[ 2  6 12]
 [ 8 15 24]]


In [51]:
# Two dimensional array - Multiplication
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[3,2,3]])
c=a*b
print(c)

[[ 2  6 12]
 [12 10 18]]


In [ ]:
****************    NumPy - Iterating Over Array     ****************

In [1]:
# Simple Iteration
import numpy as np
a = 1,2,3
for x in a:
   print (x)

1
2
3


In [2]:
# Simple Iteration
import numpy as np
a = np.arange(1,10)
for x in a:
   print (x)

1
2
3
4
5
6
7
8
9


In [30]:
# Simple array
import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
# Simple Iteration using array
import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
for x in np.nditer(a):
    print (x)

1
2
3
4
5
6
7
8
9
10
11
12


In [38]:
# Transpose of the simple array

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print(a)
print ("")
b=a.T
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [42]:
# Iterationg the transpose of the above array

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Transpose of the above array ")
b=a.T
print(b)
print ("Modified array ")
for x in np.nditer(b):
    print (x)

# Note: The order of iteration is chosen to match the memory layout of an array, 
#       without considering a particular ordering. 
#       This can be seen by iterating over the transpose of the above array.

Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose of the above array 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Modified array 
1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
# Iteration Order -  C-Style

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Transpose of the above array ")
b=a.T
print(b)

c= b.copy(order='C')
print ("Modified array ")
for x in np.nditer(c):
    print (x)

# Note: If the same elements are stored using C-style order, 
#       the iterator chooses the more efficient way of iterating over an array.



Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose of the above array 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Modified array 
1
5
9
2
6
10
3
7
11
4
8
12


In [45]:
# Iteration Order -  F-Style

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Transpose of the above array ")
b=a.T
print(b)

c= b.copy(order='F')
print ("Modified array ")
for x in np.nditer(c):
    print (x)

# Note: If the same elements are stored using F-style order, 
#       the iterator chooses the more efficient way of iterating over an array.

Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose of the above array 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Modified array 
1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
# Specific Order
# It is possible to force nditer object to use a specific order by explicitly mentioning it.

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Transpose of the above array ")
b=a.T
print(b)


for x in np.nditer(b, order='C'):
    print (x)

Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose of the above array 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
1
5
9
2
6
10
3
7
11
4
8
12


In [53]:
# Modifying Array Values using op_flags

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Modified array ")

for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*2
print (a)



Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Modified array 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [56]:
# Modifying Array Values using op_flags

import numpy as np
a = np.arange(1,13, dtype="float32")
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Modified array ")

for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=(x*25)/100
print (a)


Original array is:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Modified array 
[[0.25 0.5  0.75 1.  ]
 [1.25 1.5  1.75 2.  ]
 [2.25 2.5  2.75 3.  ]]


In [57]:
# nditer - external loop

import numpy as np
a = np.arange(1,13, dtype="float32")
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Modified array ")

for x in np.nditer(a, flags=['external_loop'], order='F'):
    print (x)
    
# Note: One-dimensional arrays corresponding to each column is traversed by the iterator.

Original array is:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Modified array 
[1. 5. 9.]
[ 2.  6. 10.]
[ 3.  7. 11.]
[ 4.  8. 12.]


In [2]:
# Broadcasting Iteration

import numpy as np
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Array 1")
print(a)
print ("Array 2 ")
b = [1,2,3,4]
print(b)
print ("Modified Array ")
for x,y in np.nditer([a,b]):
    print (x,y)
    

# Note: If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently. Assuming that an array a has dimension 3X4, and there is another array b of dimension 1X4, the iterator of following type is used (array b is broadcast to size of a).

Array 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 2 
[1, 2, 3, 4]
Modified Array 
1 1
2 2
3 3
4 4
5 1
6 2
7 3
8 4
9 1
10 2
11 3
12 4


In [ ]:
******************   NumPy - Array Manipulation    *******************

NumPy package for manipulation of elements in ndarray object

**Changing Shape
    1. reshape
    2. flat
    3. flatten
    4. ravel

** Tanspose Operation
    1. transpose
    2. ndarray.T
    3. rollaxis
    4. swapaxes


In [1]:
# ndarray.reshape - Gives a new shape to an array without changing its data

import numpy as np
a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns resize to 3 rows 2 column
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# ndarray.flat - This function returns a 1-D iterator over the array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])   
print(a.flat[5])

6


In [9]:
# ndarray.flatten - This function returns a copy of an array collapsed into one dimension.
import numpy as np
a=np.array([[1,2,3],[4,5,6]])   
print(a.flatten())    # default order is C-syle ordering

print(a.flatten(order='F'))  # Specifying F-Style order 

[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [12]:
# ndarray.ravel - This function returns a flattened one-dimensional array. The returned array will have the same type as that of the input array. The function takes one parameter.

import numpy as np
a=np.array([[1,2,3],[4,5,6]])   

print(a.ravel())

[1 2 3 4 5 6]


In [3]:
# numpy.transpose - This function permutes the dimension of the given array.

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print (a)

b=np.transpose(a)
print (b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [5]:
# numpy.ndarray.T - similar to the numpy.transpose

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print (a)

b=a.T
print (b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [6]:
# numpy.swapaxes - This function interchanges the two axes of an array. 
import numpy as np 
a = np.arange(8).reshape(2,2,2) 
print (a)
print("")
# now swap numbers between axis 0 (along depth) and axis 2 (along width)
print (np.swapaxes(a,2,0))  

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [30]:
# numpy.swapaxes - This function interchanges the two axes of an array. 
import numpy as np 
a = np.arange(8).reshape(2,2,2) 
print (a)
print("")
# now swap numbers between axis 1 (along depth) and axis 0 (along width)
print (np.swapaxes(a,0,1))  

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


In [59]:
# numpy.expand_dims - This function expands the array by inserting a new axis at the specified position.
# Example - Two Dimensional array

import numpy as np 
a = np.arange(12).reshape(4,3) 
print("Array a")
print (a)
print("")

b=np.expand_dims(a, axis=1)
print("Array b")
print(b)
print (a.shape)
print (b.shape)

# Note: Look at the output carefully to see the difference between array a and array b.
# Note: Try changing the axis to  axis=1, axis 3 etc to see difference

Array a
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Array b
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]
(4, 3)
(4, 1, 3)


In [57]:
# numpy.expand_dims - This function expands the array by inserting a new axis at the specified position.
# Example - Three Dimensional array

import numpy as np 
a = np.arange(12).reshape(3,2,2) 
print("Array a")
print (a)
print("")

b=np.expand_dims(a, axis=0)
print("Array b")
print(b)
print (a.shape)
print (b.shape)

# Note: Look at the output carefully to see the difference between array a and array b.
# Note: Try changing the axis to  axis=1, axis 3 etc to see difference

Array a
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

Array b
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]]
(3, 2, 2)
(1, 3, 2, 2)


In [64]:
# numpy.squeeze - This function removes one-dimensional entry from the shape of the given array. 

import numpy as np 
a = np.arange(8).reshape(1,2,4) 
print ('The original array:') 
print (a)
print("\n")

print ('After applying the squeeze function:') 
b=np.squeeze(a)
print(b)


The original array:
[[[0 1 2 3]
  [4 5 6 7]]]


After applying the broadcast_to function:
[[0 1 2 3]
 [4 5 6 7]]


In [70]:
# np.broadcast_to - This function broadcasts an array to a new shape.

import numpy as np 
a = np.arange(4).reshape(1,4) 

print ('The original array:') 
print (a )
print ('\n' ) 

print ('After applying the broadcast_to function:') 
print (np.broadcast_to(a,(4,4)))

The original array:
[[0 1 2 3]]


After applying the broadcast_to function:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [83]:
# numpy.concatenate - This function is used to join two or more arrays of the same shape along a specified axis.

import numpy as np 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

print ('First array:') 
print (a) 
print ('Second array:') 
print (b )

print ('Joining the two arrays along axis 0:') 
print (np.concatenate((a,b)))            # Default axis is 0 

print ('Joining the two arrays along axis 1:') 
print (np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [88]:
# numpy.stack - This function joins the sequence of arrays along a new axis.

import numpy as np 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

print ('First array:') 
print (a) 
print ('Second array:') 
print (b )

print ('Joining the sequence of two arrays along axis 0:') 
print (np.stack((a,b)))            # Default axis is 0 

print ('Joining the sequence of two arrays along axis 1:') 
print (np.stack((a,b),axis = 1))


# Note:  Look the output of numpy.concatenate and numpy.stack carefully to see the difference.

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
Joining the sequence of two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Joining the sequence of two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [92]:
# numpy.hstack - Variants of numpy.stack function to stack so as to make a single array horizontally.

import numpy as np 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

print ('First array:') 
print (a) 
print ('Second array:') 
print (b )

print ('stack horizondally') 
print (np.hstack((a,b)))        

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
stack horizondally
[[1 2 5 6]
 [3 4 7 8]]


In [93]:
# numpy.vstack - Variants of numpy.stack function to stack so as to make a single array vertically.

import numpy as np 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

print ('First array:') 
print (a) 
print ('Second array:') 
print (b )

print ('stack vertically') 
print (np.vstack((a,b)))  

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
stack vertically
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# numpy.split - This function divides the array into subarrays along a specified axis.

import numpy as np
a=np.arange(6)
print(a)

b=np.split(a,3)   # Split the array in 3 equal-sized subarrays
print(b)

b=np.split(a,[2,5])   # Split the array at positions indicated in 1-D array
print(b)

[0 1 2 3 4 5]
[array([0, 1]), array([2, 3]), array([4, 5])]
[array([0, 1]), array([2, 3, 4]), array([5])]


In [13]:
# numpy.hsplit - This function split array horizondally

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)

b=np.hsplit(a,2)   # Split the array horizondally
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [11]:
# numpy.vsplit - This function split array vertically

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)

b=np.vsplit(a,3)   # Split the array vertically
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [3]:
# numpy.resize - This function returns a new array with the specified size.

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.resize(a,[4,3])   # Resizing the array
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
# numpy.append - This function adds values at the end of an input array.

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.append(a,[[11,22,33]])   # Adding new values to the array a
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[ 0  1  2  3  4  5  6  7  8  9 10 11 11 22 33]


In [7]:
# numpy.append - This function adds values at the end of an input array.

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.append(a,[[11,22,33]])   # Adding new values to the array a
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[ 0  1  2  3  4  5  6  7  8  9 10 11 11 22 33]


In [9]:
# numpy.append -Setting axis

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.append(a,[[11,22,33,44]],axis=0)   # Adding new row values
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [11 22 33 44]]


In [22]:
# numpy.insert - This function inserts values in the input array along the given axis and before the given index.

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.insert(a,4, [11,22,33,44])   # Inserting new rows
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[ 0  1  2  3 11 22 33 44  4  5  6  7  8  9 10 11]


In [43]:
# numpy.insert - Using axis

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.insert(a, 1, [11], axis= 0 )   # Inserting new rows
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[[ 0  1  2  3]
 [11 11 11 11]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
# numpy.insert - Using axis

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.insert(a, 1, [11], axis= 1 )   # Inserting new rows
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[[ 0 11  1  2  3]
 [ 4 11  5  6  7]
 [ 8 11  9 10 11]]


In [45]:
# numpy.delete - This function returns a new array with the specified subarray deleted from the input array.

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.delete(a, 1)   # Delete a value
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[ 0  2  3  4  5  6  7  8  9 10 11]


In [47]:
# numpy.delete - Using axis

import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print ('\n Resized array') 
b=np.delete(a, 1, axis= 1 )   # Deleting a column using row
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Resized array
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [53]:
# numpy.unique - This function returns an array of unique elements in the input array.

import numpy as np
a=np.array([[1,2,1],[3,1,3],[1,1,2]])
print(a)
print('\n')

b=np.unique(a) # Unique elements in the array
print(b)

[[1 2 1]
 [3 1 3]
 [1 1 2]]


[1 2 3]


In [62]:
# numpy.unique - This function returns an array of unique elements in the input array.

import numpy as np
a=np.array([[1,2,1],[3,1,3],[1,1,2]])
print(a)
print('\n')

b=np.unique(a) # Unique elements in the array
print(b)

b,indices=np.unique(a,return_index='true')
print("\nPrintng Indices")
print (indices)

[[1 2 1]
 [3 1 3]
 [1 1 2]]


[1 2 3]

Printng Indices
[0 1 3]


In [ ]:
******************   NumPy - Binary Operators    *******************

In [5]:
# Printing Binary Numbers
import numpy as np
a=27
print (bin(a))


0b11011


In [12]:
# Bitwise AND Operator 
# Using function - bitwise_and

import numpy as np

print (np.bitwise_and(22,26))


18


In [13]:
# Bitwise OR Operator 
# Using function - bitwise_or

import numpy as np

print (np.bitwise_or(22,26))


30


In [28]:
# Bitwise NOT Operator 
# Using function - invert

import numpy as np

print (np.invert([13]))

[-14]


In [42]:
# numpy.left_shift()
# numpy.left_shift() function shifts the bits in binary representation of an array element to the left by specified positions.

import numpy as np
print (np.binary_repr(11, width = 8))

print (np.left_shift(11,2))

print (np.binary_repr(44, width = 8))


00001011
44
00101100


In [45]:
# numpy.right_shift()
# numpy.right_shift() function shifts the bits in binary representation of an array element to the right by specified positions.

import numpy as np
print (np.binary_repr(11, width = 8))

print (np.right_shift(11,2))

print (np.binary_repr(2, width = 8))


00001011
2
00000010


In [ ]:
*******************   String Functions   *********************

In [43]:
# String Concatenation
# Returns element-wise string concatenation for two arrays of str or Unicode

import numpy as np

print (np.char.add('Hello','World'))


HelloWorld


In [44]:
# String Concatenation
# Returns element-wise string concatenation for two arrays of str or Unicode

import numpy as np

print (np.char.add(['Hello','World'],['Super','Star']))

['HelloSuper' 'WorldStar']


In [45]:
# String Multiply
# Returns the string with multiple concatenation, element-wise

import numpy as np

print (np.char.multiply('Hello', 3))

HelloHelloHello


In [46]:
# np.char.center
# Returns a copy of the given string with elements centered in a string of specified length

import numpy as np

print (np.char.center('Hello', 20, fillchar='#'))

#######Hello########


In [47]:
# numpy.char.capitalize()
# Returns a copy of the string with only the first character capitalized

import numpy as np

print (np.char.capitalize('hello world'))


Hello world


In [48]:
# numpy.char.title()
# Returns the element-wise title cased version of the string or unicode

import numpy as np

print (np.char.title('hello world'))


Hello World


In [49]:
# numpy.char.lower()
# Returns an array with the elements converted to lowercase
   
import numpy as np

print (np.char.lower('HELLO WORLD'))


hello world


In [50]:
# numpy.char.upper()
# Returns an array with the elements converted to uppercase

import numpy as np

print (np.char.upper('hello world'))


HELLO WORLD


In [51]:
# numpy.char.split()
# Returns a list of the words in the string, using separatordelimiter

import numpy as np

print (np.char.split('hello how are you'))


['hello', 'how', 'are', 'you']


In [52]:
# numpy.char.split()
# Returns a list of the words in the string, using separatordelimiter

import numpy as np

print (np.char.split('hello, how, are, you'),sep=',')

['hello,', 'how,', 'are,', 'you']


In [53]:
# numpy.char.splitlines()
# Returns a list of the lines in the element, breaking at the line boundaries

import numpy as np

print (np.char.splitlines('hello\n how are you'))

['hello', ' how are you']


In [54]:
# numpy.char.strip()
# Returns a copy with the leading and trailing characters removed

import numpy as np
print (np.char.strip('hello how are you', 'h'))
print (np.char.strip('hello how are you ah', 'h'))

ello how are you
ello how are you a


In [55]:
# numpy.char.join()
# Returns a string which is the concatenation of the strings in the sequence

import numpy as np

print (np.char.join('-','hello world'))


h-e-l-l-o- -w-o-r-l-d


In [56]:
# numpy.char.join()
# Returns a string which is the concatenation of the strings in the sequence

import numpy as np

print (np.char.join(['-','+'],['hello', 'world']))

['h-e-l-l-o' 'w+o+r+l+d']


In [57]:
# numpy.char.replace()
# Returns a copy of the string with all occurrences of substring replaced by the new string

import numpy as np

print (np.char.replace('hello world', 'h','e'))

eello world


In [58]:
# numpy.char.encode()
# Calls str.encode element-wise

import numpy as np

a= np.char.encode('hello world','cp500')
print (a)


b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'


In [59]:
# numpy.char.decode()
# Calls str.decode element-wise

import numpy as np

a= np.char.encode('hello world','cp500')
print (a)

print (np.char.decode(a,'cp500'))


b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
hello world


In [ ]:
********************   Mathematical Functions    ********************

In [64]:
# Finding Sine Values

import numpy as np

print (np.sin(0))

0.0


In [67]:
# Finding Cosine Values

import numpy as np

print (np.cos(0))

1.0


In [68]:
# Finding tangent Values

import numpy as np

print (np.tan(0))

0.0


In [69]:
# Finding Sine Values for 30

import numpy as np

print (np.sin(30*np.pi/180))

0.49999999999999994


In [70]:
# Finding Cosine Values for 30

import numpy as np

print (np.cos(30*np.pi/180))

0.8660254037844387


In [73]:
# Finding Sine Values for different input

import numpy as np

a=np.array([0,30,60,90,120,150,180])
print (np.sin(a*np.pi/180))

[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]


In [74]:
# Finding Cosine Values for different input

import numpy as np

a=np.array([0,30,60,90,120,150,180])
print (np.cos(a*np.pi/180))

[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]


In [78]:
# Finding tangent Values for different input

import numpy as np

a=np.array([0,30,60,90,120,150,180])
print (np.tan(a*np.pi/180))

[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [82]:
# arcsin - Finding inverse of Sine Values for different input

import numpy as np

a=np.array([0,30,60,90,120,150,180])
b= (np.sin(a*np.pi/180))

print (np.arcsin(b))

[0.00000000e+00 5.23598776e-01 1.04719755e+00 1.57079633e+00
 1.04719755e+00 5.23598776e-01 1.22464680e-16]


In [84]:
# arccos - Finding inverse of cosine Values for different input

import numpy as np

a=np.array([0,30,60,90,120,150,180])
b= (np.cos(a*np.pi/180))

print (np.arccos(b))

[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265]


In [85]:
# arctan - Finding inverse of tangent Values for different input

import numpy as np

a=np.array([0,30,60,90,120,150,180])
b= (np.tan(a*np.pi/180))

print (np.arctan(b))

[ 0.00000000e+00  5.23598776e-01  1.04719755e+00  1.57079633e+00
 -1.04719755e+00 -5.23598776e-01 -1.22464680e-16]


In [95]:
# Rounding off
import numpy as np

a=np.array([0,30,60,90,120,150,180])
b= (np.sin(a*np.pi/180))

print(np.arcsin(b))
c=np.arcsin(b)

print(np.round(c))

print(np.round(c,decimals=3))

[0.00000000e+00 5.23598776e-01 1.04719755e+00 1.57079633e+00
 1.04719755e+00 5.23598776e-01 1.22464680e-16]
[0. 1. 1. 2. 1. 1. 0.]
[0.    0.524 1.047 1.571 1.047 0.524 0.   ]


In [ ]:
************************   Arithmetic Operation   ***********************

In [101]:
# Array Addition

import numpy as np

a=np.arange(9).reshape(3,3)
print (a)

b=np.arange(3).reshape(3,1)
print (b)

print(np.add(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [103]:
# Array Subtraction

import numpy as np

a=np.arange(9).reshape(3,3)
print (a)

b=np.arange(3).reshape(3,1)
print (b)

print(np.subtract(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [2 3 4]
 [4 5 6]]


In [104]:
# Array Multiplication

import numpy as np

a=np.arange(9).reshape(3,3)
print (a)

b=np.arange(3).reshape(3,1)
print (b)

print(np.multiply(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]


In [121]:
# Array Division

import numpy as np

a=np.arange(3,12).reshape(3,3)
print (a)

b=np.arange(3,6).reshape(3,1)
print (b)

print(np.divide(a,b))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3]
 [4]
 [5]]
[[1.         1.33333333 1.66666667]
 [1.5        1.75       2.        ]
 [1.8        2.         2.2       ]]


In [125]:
# Reciprocal of an array

import numpy as np

a = np.array([0.75, 0.373, 3.3, 0.2]) 
print (a)

print(np.reciprocal(a))

[0.75  0.373 3.3   0.2  ]
[1.33333333 2.68096515 0.3030303  5.        ]


In [126]:
# numpy.power
import numpy as np

a = np.array([0,1,2,3]) 
print (a)

print(np.power(a,2))

[0 1 2 3]
[0 1 4 9]


In [127]:
# numpy.power
import numpy as np

a = np.array([0,1,2,3]) 
print (a)

print(np.power(a,5))

[0 1 2 3]
[  0   1  32 243]


In [131]:
# numpy.mod and # numpy.remainder
import numpy as np

a = np.array([0,10,20,30]) 
b = np.array([1,3,6,7])

print(np.mod(a,b))
print(np.remainder(a,b))

[0 1 2 2]
[0 1 2 2]


In [146]:
# numpy.real() − returns the real part of the complex data type argument.
import numpy as np 
a = np.array([0.6+3j, -2.4, 3.3j , 1+11j]) 

print (a )

print (np.real(a)) 

[ 0.6 +3.j  -2.4 +0.j   0.  +3.3j  1. +11.j ]
[ 0.6 -2.4  0.   1. ]


In [145]:
# numpy.imag() − returns the imaginary part of the complex data type argument.

import numpy as np 
a = np.array([0.6+3j, -2.4, 3.3j , 1+11j]) 

print (a )

print (np.imag(a)) 

[ 0.6 +3.j  -2.4 +0.j   0.  +3.3j  1. +11.j ]
[ 3.   0.   3.3 11. ]


In [144]:
# numpy.conj() − returns the complex conjugate, which is obtained by changing the sign of the imaginary part.

import numpy as np 
a = np.array([0.6+3j, -2.4, 3.3j , 1+11j]) 

print (a )

print (np.conj(a)) 

[ 0.6 +3.j  -2.4 +0.j   0.  +3.3j  1. +11.j ]
[ 0.6 -3.j  -2.4 -0.j   0.  -3.3j  1. -11.j ]


In [143]:
# numpy.angle() − returns the angle of the complex argument. The function has degree parameter. If true, the angle in the degree is returned, otherwise the angle is in radians.
import numpy as np 
a = np.array([0.6+3j, -2.4, 3.3j , 1+11j]) 

print (a )

print (np.angle(a)) 
print (np.angle(a,deg=True)) 

[ 0.6 +3.j  -2.4 +0.j   0.  +3.3j  1. +11.j ]
[1.37340077 3.14159265 1.57079633 1.48013644]
[ 78.69006753 180.          90.          84.80557109]


In [ ]:
*********************     NumPy - Statistical Functions    ***********************

In [2]:
# numpy.amin - return the minimum from the elements in the given array

import numpy as np

a=np.array([1,2,3])
print(np.amin(a))

1


In [3]:
# numpy.amax - return the maximum from the elements in the given array

import numpy as np

a=np.array([1,2,3])
print(np.amax(a))

3


In [8]:
# numpy.amin - return the minimum from the elements in the given array

import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.amin(a,0))

[1 2 3]


In [10]:
# numpy.amin - return the minimum from the elements in the given array

import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.amin(a,1))

[1 4 7]


In [11]:
# numpy.amax - return the maximum from the elements in the given array

import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.amax(a,0))

[7 8 9]


In [12]:
# numpy.amax - return the maximum from the elements in the given array

import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.amax(a,1))

[3 6 9]


In [13]:
#  numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

import numpy as np

a=np.array([1,2,3])  # 3-1 = 2
print(np.ptp(a))

2


In [14]:
#  numpy.ptp() function returns the range (maximum-minimum) of values along an axis.
import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.ptp(a,1))

[2 2 2]


In [15]:
#  numpy.ptp() function returns the range (maximum-minimum) of values along an axis.
import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.ptp(a,0))

[6 6 6]


In [20]:
# Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall.
import numpy as np

a=np.array([1,2,3])
print(np.percentile(a,10))


1.2000000000000002


In [21]:
# Percentile
import numpy as np

a=np.array([1,2,3])
print(np.percentile(a,100))

3.0


In [24]:
# Percentile
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.percentile(a,100))

90.0


In [25]:
# Percentile
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.percentile(a,100,0))

[70. 80. 90.]


In [26]:
# Percentile
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.percentile(a,100,1))

[30. 60. 90.]


In [28]:
# Median is defined as the value separating the higher half of a data sample from the lower half.

import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.median(a))


50.0


In [29]:
# Median
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.median(a,1))

[20. 50. 80.]


In [30]:
# Median
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.median(a,0))

[40. 50. 60.]


In [31]:
# The numpy.mean() function returns the arithmetic mean of elements in the array.

import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.mean(a))

50.0


In [33]:
# numpy.mean() 

import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.mean(a,1))

[20. 50. 80.]


In [32]:
# numpy.mean() 

import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.mean(a,0))

[40. 50. 60.]


In [34]:
# numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array.

import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.average(a,0))

[40. 50. 60.]


In [38]:
# Weighted average
# 10*1+20*2+30*3 / 1+2+3

import numpy as np

a=np.array([10,20,30])
b=np.array([1,2,3])
print(np.average(a, weights=b))

23.333333333333332


In [40]:
# Weighted average
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([1,2,3])
print(np.average(a,1, weights=b))

[23.33333333 53.33333333 83.33333333]


In [41]:
# Weighted average
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([1,2,3])
print(np.average(a,0, weights=b))

[50. 60. 70.]


In [42]:
# Standard deviation is the square root of the average of squared deviations from mean.

import numpy as np

a=np.array([10,20,30])
print(np.std(a))


8.16496580927726


In [43]:
# Standard deviation
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.std(a,1))


[8.16496581 8.16496581 8.16496581]


In [44]:
# Standard deviation
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.std(a,0))

[24.49489743 24.49489743 24.49489743]


In [ ]:
# Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). 

In [45]:
import numpy as np

a=np.array([10,20,30])
print(np.var(a))


66.66666666666667


In [47]:
# Variance
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.var(a,0))

[600. 600. 600.]


In [ ]:
************    NumPy - Sort, Search & Counting Functions  ***********

In [ ]:
# numpy.sort()  -  The sort() function returns a sorted copy of the input array.
# numpy.sort(a, axis, kind, order)

In [48]:
# numpy.sort()

import numpy as np

a=np.array([3,4,6,1,3,9,0,1,4,8])
print(np.sort(a))   # default - quicksort

[0 1 1 3 3 4 4 6 8 9]


In [54]:
# numpy.sort() - merge sort

import numpy as np

a=np.array([3,4,6,1,3,9,0,1,4,8])
print(np.sort(a,0,'mergesort'))

[0 1 1 3 3 4 4 6 8 9]


In [55]:
# numpy.sort() - heap sort

import numpy as np

a=np.array([3,4,6,1,3,9,0,1,4,8])
print(np.sort(a,0,'heapsort'))

[0 1 1 3 3 4 4 6 8 9]


In [56]:
# numpy.argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. 

import numpy as np

a=np.array([3,4,6,1,3,9,0,1,4,8])
print(np.argsort(a))

[6 3 7 0 4 1 8 2 9 5]


In [70]:
# numpy.lexsort() - function performs an indirect sort using a sequence of keys.

import numpy as np

a=np.array(['ddd','bbb','ccc'])
b=np.array(['a','b','c'])
c=np.lexsort((b,a))
print (c)
print([a[i] for i in c])

[1 2 0]
['bbb', 'ccc', 'ddd']


In [1]:
# numpy.nonzero() function returns the indices of non-zero elements in the input array.

import numpy as np

a=np.array([[10,20,0],[40,50,60],[70,80,90]])
print(np.nonzero(a))

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 0, 1, 2, 0, 1, 2]))


In [2]:
#numpy.where() - The where() function returns the indices of elements in an input array where the given condition is satisfied.

import numpy as np

a=np.array([[10,20,0],[40,50,60],[70,80,90]])
print(np.where(a>30))

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))


In [4]:
# numpy.extract() - The extract() function returns the elements satisfying any condition.
import numpy as np

a=np.array([[10,20,0],[40,50,60],[70,80,90]])

condition = np.mod(a,3)==0
print(np.extract(condition,a))


[ 0 60 90]


In [17]:
# numpy.ndarray.byteswap() - The numpy.ndarray.byteswap() function toggles between the two representations: bigendian and little-endian.
import numpy as np

a=np.array([10,20,0])

print(a.byteswap(True))
print(a.byteswap(True))


[ 720575940379279360 1441151880758558720                   0]
[10 20  0]


In [ ]:
***************** Numpy Copies and Views  ******************

In [ ]:
# id() - The id() returns a universal identifier of Python object, similar to the pointer in C.
# Furthermore, any changes in either gets reflected in the other. 

In [36]:
import numpy as np
a=np.arange(6).reshape(2,3)
print(a)

id(a)

b=a
print(b)

b.shape = 3,2  # Changes will be reflected in both variable

print(b)
print(a) 

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [37]:
# ndarray.view() method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn’t change dimensions of the original.

import numpy as np
a=np.arange(6).reshape(2,3)
print(a)

id(a)

b=a.view()
print(b)

b.shape = 3,2  # Changes will not be reflected in both variable

print(b)
print(a) 

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [40]:
#ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

import numpy as np
a=np.arange(6).reshape(2,3)
print(a)

id(a)

b=np.copy(a)
print(b)

b[1,0]=50  # Changes will not be reflected in both variable

print(b)
print(a) 

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [50  4  5]]
[[0 1 2]
 [3 4 5]]


In [ ]:
****************  I/O with NumPy   ****************

In [2]:
# numpy.save() - The numpy.save() file stores the input array in a disk file with npy extension.

import numpy as np 
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)


In [4]:
# numpy.load() - To reconstruct array from outfile.npy, use load() function.
import numpy as np 
b = np.load('outfile.npy') 
print (b )

[1 2 3 4 5]


In [11]:
# The storage and retrieval of array data in simple text file format is done with savetxt() and loadtxt() functions.
import numpy as np 

a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print (b) 

[1. 2. 3. 4. 5.]
